### ISSUE TITLE
感谢彩虹屁这个创意

### ISSUE THREAD

**Issue by ezshine** [SaekiRaku/vscode-rainbow-fart#102]
感谢彩虹屁的创意，我重新开发了HBuilderX的插件去参加DCloud插件开发大赛。
https://ext.dcloud.net.cn/plugin?id=2157#detail
如果有幸获得奖金，我要分彩虹屁团队一半。

在开发中，我找到以下方式可以不用web来播放语音。
macos："afplay mp3filepath"
windwos：内嵌cmdmp3.exe   "cmdmp3.exe mp3filepath"

不知道彩虹屁在vscode下是否可以用这个方式播放音频。

**Comment by SaekiRaku** [comment]
目前可以实现的方法有很多，详见：https://github.com/SaekiRaku/vscode-rainbow-fart/issues/34 ，但是我这边更多的是考虑用户会如何使用这个插件。因为很大的插件体积或前置依赖体积会导致漫长的下载时间，而对于这样一款娱乐性大于实用性的插件，用户未必愿意付出这些时间等待插件就绪。所以目前依然使用通过浏览器播放的方案。另见： https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#能否不通过浏览器直接播放音频？

**Comment by ezshine** [comment]
我采用的方案对体积的影响几乎为零。你可以参考下....

**Comment by ezshine** [comment]
在mac下，是系统默认的afplay来播放音频。在windows下，cmdmp3.exe只有26kb大小哦。
