### ISSUE TITLE
关于time函数输出的问题

### ISSUE THREAD

**Issue by racherisgenius** [SaekiRaku/vscode-rainbow-fart#104]
每小时并不会输出我设置的语音，反而是小姐姐的。（即，如果不能播放某个mp3文件的话，则会变成小姐姐的语音）
一开始我以为是我time相关函数的voice语音文件名应该按照小姐姐mainfest中的time_hour/time_evening格式改，但是改好后还是会随机出现自定义语音包不能被播放的情况。
不知道这个问题是不是只有我一个人有……？
我反复查看了一下我的文件名，也确认过在网页下每个自定义设置的语音都可以被播放，但是不是很确定问题在哪里？
希望可以指点一定time函数对应的文件名应该怎么写和如何获取文件中的语音的。（虽然看了源代码，但是感觉voice文件名并不影响输出的内容？）
抱歉，自己还是个小菜鸡，也可能上述是自己mainfest或者文件的问题，希望可以得到作者的帮助。
感谢

**Comment by SaekiRaku** [comment]
您好，导入的自定义语音包要在web界面里激活一下（每个语音包列表项右上角的开关），激活多个语音包后如果遇到共有的关键字设置，会从所有的激活语音包中匹配的语音资源里随机。你可以禁用其他所有语音包，来确保自己的语音包总是被使用。

**Comment by racherisgenius** [comment]
您好！感谢您百忙中的回复！

的确我只激活了我自己的语音包，并没有激活小姐姐或者别的语音包。所以我在使用的时候突然听到小姐姐的声音感觉很奇怪，因为自己并没有启动小姐姐的语音包。

在普通关键字的检测上，的确会输出我自己设置的语音（在只开一个自定义的语音包的情况下）。
但是在遇到整点或者time_morning，time_evening此类的函数keyword（？），就会出现俩个语音包都随机出现的现象。（有的时候会俩个语音包中一个出一条，有的时候只会出现一个未激活的语音包中的语音）同样是在我只打开一个自定义语音包的情况下。

不知道我的描述是否清楚。如果我的描述不清楚的话，我今天晚上试试录屏发给您看一下，这样可能会更直观一些。
再次，非常感谢您的回复。

**Comment by SaekiRaku** [comment]
Hi，感谢你的跟进，这是一个BUG，忘记在 `timerHook` 部分过滤未启用的语音包了。已在 1.2.5 版本上修复，并推送到了微软应用商店。
