### ISSUE TITLE
[语音包] 岛市老八 美食家 语音扩展包

### ISSUE THREAD

**Issue by fz6m** [SaekiRaku/vscode-rainbow-fart#106]
原 声 大 碟 内 容：

* 美食家
* 三次世界大战
* 口区乐器
* 大量战斗原声

老铁们昂，只有你们想不到带，没有老八 zhuo 不到 dia ！

前往 [撤硕](https://github.com/fz6m/laoba-rainbow-fart) 下载（

**Comment by madaoCN** [comment]
niubility，哈哈哈

**Comment by heavenly-zy** [comment]
韩信带净化，只有你们想不到的，永远没有老八做不到的，奥利给，干了兄弟们

**Comment by ybyllc** [comment]
呕！奥里给，干了兄弟们！

**Comment by larrryCCC** [comment]
撤硕是空的？

**Comment by fz6m** [comment]
> 撤硕是空的？

<img src='https://user-images.githubusercontent.com/59400654/148780521-d8991703-1c8d-4c6d-b32b-c36c1248b5e4.jpg' width='50%' />
