### ISSUE TITLE
[Question] 关键字触发问题

### ISSUE THREAD

**Issue by alanleung2017** [SaekiRaku/vscode-rainbow-fart#107]
是不是只适配js的关键字，其它语言的呢

**Comment by SaekiRaku** [comment]
目前内置语音包增加了一部分 python、golang 的关键字，但是与之匹配的语音资源的增加相对比较困难。

请参阅文档 常见问题 部分：
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#能否支持更多的语言编辑器ide
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#如何修改内置语音包（增加修改关键字等）
