### ISSUE TITLE
怎么不支持golang开发

### ISSUE THREAD

**Issue by tddey01** [SaekiRaku/vscode-rainbow-fart#109]
没有找到 golang 语音提示 
请作者 添加支持golang开发提示

**Comment by SaekiRaku** [comment]
请参阅：
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2#issuecomment-645780763
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#能否支持更多的语言编辑器ide
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#如何修改内置语音包（增加修改关键字等）
