### ISSUE TITLE
考虑支持一下IDEA吧，用户量老大了，大佬

### ISSUE THREAD

**Issue by hhb1san14** [SaekiRaku/vscode-rainbow-fart#11]
考虑支持一下IDEA吧，用户量老大了，大佬

**Comment by ulrica-ai** [comment]
> 考虑支持一下IDEA吧，用户量老大了，大佬

是的是的 需求很旺盛

**Comment by twelife** [comment]
idea表示很需要

**Comment by SaekiRaku** [comment]
抱歉，平时工作中主要使用 VSCode，对其他 编辑器/IDE 的开放 API 不太熟悉。插件移植是在计划中的，但是可能会需要较长的时间。如果有熟悉其他任意编辑器或IDE的开放API的开发者，欢迎提交PR。目前我这边可以做的就是尽快独立核心模块，使插件移植更方便一些。

Similar with:
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/6
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/3#issuecomment-645786218

**Comment by FFzt** [comment]
附议

**Comment by izhangzhihao** [comment]
WIP: https://github.com/izhangzhihao/intellij-rainbow-fart

**Comment by izhangzhihao** [comment]
试试这个snapshot版本：https://app.circleci.com/pipelines/github/izhangzhihao/intellij-rainbow-fart/2/workflows/81855129-bbd6-4ba7-af44-7022d20c05ab/jobs/2/artifacts

需要用github登陆，还在修改中。

**Comment by izhangzhihao** [comment]
基本功能已经支持了，欢迎大家下载试用！

**Comment by izhangzhihao** [comment]
已经发布了一个版本，可以在[这里](https://github.com/izhangzhihao/intellij-rainbow-fart/releases)下载了🌈

**Comment by dgk1024** [comment]
同求idea

**Comment by SaekiRaku** [comment]
> 已经发布了一个版本，可以在[这里](https://github.com/izhangzhihao/intellij-rainbow-fart/releases)下载了🌈

@dgk1024 试试这个

**Comment by Sirlanri** [comment]
@izhangzhihao 已经实现了IDEA的彩虹屁，idea用户们可以资瓷一下哦

**Comment by juck73** [comment]
臣附议

**Comment by SaekiRaku** [comment]
Closed, please refer to https://github.com/izhangzhihao/intellij-rainbow-fart

**Comment by jadepeng** [comment]
这里写了一款https://github.com/jadepeng/idea-rainbow-fart，兼容vscode的语音包，欢迎使用
