### ISSUE TITLE
[BUG] 服务器掉线后, 浏览器网页会导致CPU上升

### ISSUE THREAD

**Issue by smsn** [SaekiRaku/vscode-rainbow-fart#110]
![2020-07-01 23-32-06屏幕截图](https://user-images.githubusercontent.com/16523929/86264071-a3a2ef00-bbf4-11ea-8fb6-b4ea43fb4149.png)

**Comment by SaekiRaku** [comment]
Thanks for your feedback. This bug has been fixed with the newly released version v1.4.0.
