### ISSUE TITLE
[BUG] Translate/Language error 【中文翻译错别字】

### ISSUE THREAD

**Issue by CTFer** [SaekiRaku/vscode-rainbow-fart#113]
The chinese description of rainbow fart has a error .
【一个在你编程时疯狂夸你写**的**（得）牛逼的VScode扩展】

**Comment by shadowings-zy** [comment]
说起Language Error，我在使用这款插件的时候发现
`it's mean give somebody exaggerated compliment that even seems a little fake`
这一句也有些问题，修改成
`it means giving somebody exaggerated compliment which even seems a little fake`
会比较好一些

要不我提一个PR吧hhhh

**Comment by SaekiRaku** [comment]
@shadowings-zy Thanks for the PR.
