### ISSUE TITLE
[Feature] 限制查找端口号次数，并且当检查端口号出错后，提示相应信息

### ISSUE THREAD

**Issue by Huoshendameng** [SaekiRaku/vscode-rainbow-fart#117]
**Describe your request**
![image](https://user-images.githubusercontent.com/17901087/86510315-3f18a780-be21-11ea-818e-cae23201a00a.png)

**Comment by SaekiRaku** [comment]
👍 GOOD thinking!

**Comment by SaekiRaku** [comment]
Thanks for your feedback. This feature has been added with the newly released version v1.4.0.
