### ISSUE TITLE
How to trigger the "time" sound

### ISSUE THREAD

**Issue by tianqifeiyang** [SaekiRaku/vscode-rainbow-fart#125]
How to trigger the "time" sound, I found the it will say "why aren't you off duty " in the show video by input //21:00

But, I can not reproduce it, Could you please share more information about how to trigger the keyword "time"

Many thanks！

**Comment by SaekiRaku** [comment]
Hi, thanks for your feedback. Actually, it will trigger when your computer time hit to 9 o'clock PM, the example video didn't show that clearly, sorry for misleading you.

(Duplicated with https://github.com/SaekiRaku/vscode-rainbow-fart/issues/36)
