### ISSUE TITLE
能不能提供个语音包的接口，或者多提供一些语音包

### ISSUE THREAD

**Issue by KRISACHAN** [SaekiRaku/vscode-rainbow-fart#13]
R.T.

**Comment by SaekiRaku** [comment]
感谢关注，目前语音包开放了一些简单的定制能力，详见文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md ，后续我会继续完善相关内容。

**Comment by KRISACHAN** [comment]
> 感谢关注，目前语音包开放了一些简单的定制能力，详见文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md ，后续我会继续完善相关内容。
> 
> Thanks for your attention. At present, the voice package have some simple customization capabilities, see: https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md I will keep update in the future.

哈哈哈，大佬回复真快

**Comment by seachenjy** [comment]
你是想要嗯嗯啊啊之类的语音包吧，得自己去p站截取

**Comment by jadepeng** [comment]
https://github.com/jadepeng/rainbow-fart-tts
这里自定义语音包
