### ISSUE TITLE
可能女性程序员不会喜欢

### ISSUE THREAD

**Issue by sundevilyang** [SaekiRaku/vscode-rainbow-fart#14]
看了下里面的demo视频，假定写代码的人都是男的，会说「怎么还没有下班，应该多关注身边的女孩子」。

建议：可以再出个男声版本。男声版本的内容也做适当修改，贴近女性程序员的需求。

**Comment by SaekiRaku** [comment]
@sundevilyang 项目本身是期望多元化的，如果不喜欢某个台词、某个声音、某个语种、某个性格等等，都可以禁用语音包替换其他的，但是更多的语音内容需要大量的时间和经理，所以目前内置的语音包并不是很丰富。我目前能做的只能是完善语音包的配置文档、标准等，期望开源社区可以贡献更多不同声音的语音包。

**Comment by sundevilyang** [comment]
👍 

我来帮你在 http://codingirlsclub.com/ 宣传下，看CGC社群有没有志愿者来贡献。

**Comment by SaekiRaku** [comment]
@sundevilyang 🙏非常感谢，项目启动不久，还需要做很多事情。
