### ISSUE TITLE
可否考虑支持一下C++呀

### ISSUE THREAD

**Issue by Wonderperson** [SaekiRaku/vscode-rainbow-fart#16]

**Comment by SaekiRaku** [comment]
感谢反馈，插件本身没有对编辑的文件类型进行判断，所以，一些通用关键字也是可以触发语音的（例如 if, for）。但是，针对特定语言的更多语音需要大量的时间和精力来维护。我个人是更期望由开源社区贡献语音包的。另附：https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2

**Comment by SaekiRaku** [comment]
Closed due to duplicate with https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2
