### ISSUE TITLE
语音内容不科学

### ISSUE THREAD

**Issue by wenchangping** [SaekiRaku/vscode-rainbow-fart#17]
1.部分语音并未夸我，如**再多循环都不能循环我的可爱。
2.部分语音带有嘲讽，如**你就是想太多如果，才找不到女朋友吧，要泪目了，亲

**Comment by SaekiRaku** [comment]
😂 文案确实不太好想，如果有好的彩虹屁文案，欢迎分享。

**Comment by tuzimoe** [comment]
请参考 https://chp.shadiao.app/

**Comment by sadmess** [comment]
离谱啊兄弟
