### ISSUE TITLE
只有萌妹纸的声音吗？

### ISSUE THREAD

**Issue by W-alex** [SaekiRaku/vscode-rainbow-fart#20]
有没有帅酷帅酷的弟弟的声音呢？

**Comment by SaekiRaku** [comment]
感谢反馈，因为人力有限，内置语音包的内容不是很丰富。但是目前开放了一部分的定制能力，欢迎贡献身边的男性程序员录制语音😂。

另附：
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/13
