### ISSUE TITLE
闲的蛋疼做了个语音包, 应该没人会用吧 😂

### ISSUE THREAD

**Issue by zszen** [SaekiRaku/vscode-rainbow-fart#22]
[zszen-boy-voice-chinese.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4804371/zszen-boy-voice-chinese.zip)

cmd+shift+p 开启彩虹屁
点击网页的导入语音包
选择打开语音包目录, 删掉默认语音包(建议备份, 后悔可以换回来😂) , 作者好像没有放选择语音包功能

![图片](https://user-images.githubusercontent.com/1890538/85128768-88cf9280-b264-11ea-92f3-de0e28c7fb3d.png)

**Comment by SaekiRaku** [comment]
感谢贡献！启用/禁用语音包的功能将在下一个版本增加（实际上目前主分支的版本已经含带此功能了，可以克隆主分支 `npm install && npm run build` 自行编译安装）。

语音包目录的内置语音其实也是一个副本，真正的语音文件包含在插件本身了，即使删除了下次启动时依然会复制过去。

**Comment by izhangzhihao** [comment]
建议有一个集中的仓库存储统一格式的语音包，并且每个语音包最好都要有`contributes.json`，这样可以直接在插件中加载列表，用户可以直接选择。

**Comment by SaekiRaku** [comment]
> @izhangzhihao 
> 建议有一个集中的仓库存储统一格式的语音包，并且每个语音包最好都要有`contributes.json`，这样可以直接在插件中加载列表，用户可以直接选择。

目前语音包资源还比较少，我可以先通过文档的方式手动维护，后期可以考虑维护一个语音包列表的仓库。

**Comment by Yunfeng-Song** [comment]
做个郭德纲语音包 不然举报了：）

**Comment by izhangzhihao** [comment]
> 做个郭德纲语音包 不然举报了：）

"就您这样儿的，还上什么班啊"

**Comment by SaekiRaku** [comment]
Closed due to no more reply, and also, this page's link is already added to the document: [Awesom Rainbowfart](https://saekiraku.github.io/vscode-rainbow-fart/#/zh/#更多炫酷彩虹屁)
