### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by JiaXueYan** [SaekiRaku/vscode-rainbow-fart#26]
安装报错

**Comment by SaekiRaku** [comment]
This seems like the extension is not fully downloaded, probably is beacuse the network problem. Please try to rename the extension name to `.zip` and unzip. If unzipping is succeeded, please click the `Help` menu on VSCode, and click `About`, then provide the system and version information on it.

---

这个错误看起来像是安装包没有下载完整，有可能是访问 GitHub 的网络问题导致的。请您尝试一下将安装包后缀名改为 .zip 然后解压它看看能否成功。如果正常解压，请点击 VSCode 的 `帮助` 菜单，然后点击关于，提供一下弹出窗口的系统及版本信息。

**Comment by SaekiRaku** [comment]
Close due to no more respond, feel free to reopen this issue.
