### ISSUE TITLE
您好，请问远程访问服务器的情况下，怎么能正常使用该插件？

### ISSUE THREAD

**Issue by wang1104014663** [SaekiRaku/vscode-rainbow-fart#27]
显示插件本地禁用

**Comment by SaekiRaku** [comment]
<img width="921" alt="QQ20200621-112156@2x" src="https://user-images.githubusercontent.com/12109558/85215954-a8280600-b3b1-11ea-8cfd-a04377fe214f.png">

抱歉，回复稍慢了一些。我这边测试了一下 VSCode Remote，只需要在扩展中点击 在 SSH:**** 中安装即可，安装后通过 "> Enable Rainbow Fart" 启用，依然是在本机启动 HTTP 服务提供页面访问及音频播放，个人测试可以正常使用。

**Comment by SaekiRaku** [comment]
<img width="915" alt="QQ20200621-112707@2x" src="https://user-images.githubusercontent.com/12109558/85215993-27b5d500-b3b2-11ea-84cd-c39b7ce11ced.png">

@wang1104014663 抱歉，回复稍慢了一些。我这边测试了一下 VSCode Remote，只需要在扩展中点击 在 SSH:**** 中安装即可（如图），安装后通过 "> Enable Rainbow Fart" 启用，依然是在本机启动 HTTP 服务提供页面访问及音频播放，个人测试可以正常使用。

**Comment by amsteel** [comment]
远程安装后，Enable 的时候提示没有发现可用端口。本地使用的是7777端口。输入后提示 “Can't enable Rainbow Fart, please retry." ubuntu 20.04, vscode 1.64.2. Raibow Fart 1.4.1
大佬指点一下？
