### ISSUE TITLE
支持多种语言的关键字

### ISSUE THREAD

**Issue by axetroy** [SaekiRaku/vscode-rainbow-fart#28]
应该针对不同语言的关键字进行播报

例如 `function` 关键字在 js 里，可是在其他语言的关键字可能是 `fn` 或者 `func`

所以如果能针对不同语言的关键字，那肯定是极好的

**Comment by SaekiRaku** [comment]
感谢反馈，我会在之后的版本，让内置语音包尽可能的适配常见语言的常用关键字。理想情况下，如果社区有较多的语音包贡献，基本上也足够覆盖大部分语言的关键字。

Similar with: https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2
