### ISSUE TITLE
发布到插件商店和vsx商店完全没问题的

### ISSUE THREAD

**Issue by trotsky1997** [SaekiRaku/vscode-rainbow-fart#30]
VScode和几款核心插件的开发基本上都是微软中国的人,比如coderrunner的韩俊老师

**Comment by SaekiRaku** [comment]
感谢您的关注！现已发布到 VSCode 商店：https://marketplace.visualstudio.com/items?itemName=saekiraku.rainbow-fart

Duplicated with: https://github.com/SaekiRaku/vscode-rainbow-fart/issues/4
