### ISSUE TITLE
支不支持代码语音报错?报错处理建议等?

### ISSUE THREAD

**Issue by 0x018** [SaekiRaku/vscode-rainbow-fart#31]
1.支不支持代码语音报错?
有时候命令行,console报错等不一定看得到, 对特定的一些报错可以语音提示

2.对一些报错自动提供建议等
一些固定错误的自定义提示,
一些莫名其妙的错误,询问是否自动打开stackoverflow,google查询等

**Comment by SaekiRaku** [comment]
错误提示需要有词法分析甚至编译过程，而面对种类繁多的编程语言引入各类 AST 库，会使插件体积迅速增大。这件事更适合拆分成更小的扩展插件来实现。不过，最主要的一点是，这是一个娱乐向的插件，类似错误提示这种实用的功能，建议使用更专业的插件来解决。

**Comment by 0x018** [comment]
> 错误提示需要有词法分析甚至编译过程，而面对种类繁多的编程语言引入各类 AST 库，会使插件体积迅速增大。这件事更适合拆分成更小的扩展插件来实现。不过，最主要的一点是，这是一个娱乐向的插件，类似错误提示这种实用的功能，建议使用更专业的插件来解决。

没让你自己写个词法分析啊,检测命令行报错, 检测浏览器 console报错
