### ISSUE TITLE
多来点语音包好吗？秋梨膏！！

### ISSUE THREAD

**Issue by DeeJay0921** [SaekiRaku/vscode-rainbow-fart#33]
rt

**Comment by Sirlanri** [comment]
#22 
可以试试导入语音包，后续应该会搞语音仓库 :)

**Comment by SashiRin** [comment]
wdnmd我都傻了
可以考虑来一套茄子的

**Comment by tediorelee** [comment]
> wdnmd我都傻了
> 可以考虑来一套茄子的

写代码也白给嗷

**Comment by angry-shark** [comment]
没有卢本伟广场？

**Comment by wendingp** [comment]
没有哲♂学语音包?

**Comment by SaekiRaku** [comment]
Closed due to no more reply. And, for now, we have got more voice packages, you can find theme at here: https://saekiraku.github.io/vscode-rainbow-fart/#/zh/awesome-rainbow-fart.md
