### ISSUE TITLE
如果快速触发语音会导致卡死

### ISSUE THREAD

**Issue by JianboYan** [SaekiRaku/vscode-rainbow-fart#35]
比如：连续输入 shit shit shit shit就会卡死。

**Comment by SaekiRaku** [comment]
感谢反馈。请问是什么浏览器？目前我这边已知 Safari 会有这个问题，倒不是连续触发导致的，而是浏览器挂在后台，周期请求自动就中断了。中断后的判断那块写的确实有点问题，还没改。

**Comment by JavaCS3** [comment]
需要debounce

**Comment by haotian-wang** [comment]
产品经理已经被打晕了，哈哈

**Comment by SaekiRaku** [comment]
Closed due to no more information, feel free to reopen.
