### ISSUE TITLE
[Question] How can I contribute to English speaking for this project?

### ISSUE THREAD

**Issue by cameronapak** [SaekiRaku/vscode-rainbow-fart#351]
**Describe your question**
 
The webpage for this VS Code extension mentions: 

> "Because I don't have any friends that use English as mother language, if you are interested in this project, it would be nice to have contribute with your voice, no matter about gender, tone color, personality, language, contry etc."

I am happy to contribute my voice to this. How can I help? I couldn't find any contact info, so this is my best attempt to reach you.

**Comment by SaekiRaku** [comment]
Thank you! Here is the format document of the Voice Package：https://saekiraku.github.io/vscode-rainbow-fart/#/en/voice-packages.md
