### ISSUE TITLE
[Question] 中科天齐Wukong(悟空)声称 rainbow fart 具有漏洞，请问这会影响用户吗？

### ISSUE THREAD

**Issue by gledos** [SaekiRaku/vscode-rainbow-fart#356]
中科天齐Wukong(悟空)声称 rainbow fart 具有漏洞，请问这会影响用户吗？

> 最后，确定了名为Rainbow Fart的扩展程序具有zip slip漏洞，该漏洞使攻击者可以覆盖受害者计算机上的任意文件，并获得远程执行代码权限。一个特殊制作的ZIP文件通过插件使用的“import-voice-package”端点发送，并被写入扩展的工作目录之外的位置。这种攻击可能被用来覆盖‘.Bashrc’并获得远程代码执行权限。

[VSCode扩展发现新漏洞 代码安全检测防御软件威胁 - 中科天齐Wukong(悟空)](https://www.woocoom.com/b021.html?id=751c7b09e8b24d14b1349ecac08f1f71)

**Comment by SaekiRaku** [comment]
您好，此漏洞已由 Snyk Security 的 Kirill 反馈。并已在最新版本修复，请及时更新。相关提交记录：https://github.com/SaekiRaku/vscode-rainbow-fart/commit/788806463f9890c1fd65d8cffd620983e7276cfe
