### ISSUE TITLE
$time_morning 这种关键词的怎么触发啊

### ISSUE THREAD

**Issue by 1124219777** [SaekiRaku/vscode-rainbow-fart#36]
我看视频上面输入时间会触发， 但是我输入后并没有触发

**Comment by SaekiRaku** [comment]
视频上演示的不够明确，实际上是到了指定时间触发的。比如早中晚，问好、提醒定外卖、提醒下班等等。

P.S. 后期会加入手动设置提醒的时间节点的功能。
