### ISSUE TITLE
打开网址404，请问怎么解决？

### ISSUE THREAD

**Issue by xuya227939** [SaekiRaku/vscode-rainbow-fart#37]
http://127.0.0.1:7777/  ，返回404

**Comment by SaekiRaku** [comment]
@xuya227939 感谢反馈，麻烦提供一下插件版本号和系统版本号（VSCode 菜单：帮助 - 关于）

**Comment by xuya227939** [comment]
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (2 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by xuya227939** [comment]
已解决，端口被占用。

**Comment by SaekiRaku** [comment]
@xuya227939 Emm...😂好吧，我的各个版本和系统都和你的一致，试了半天也没法复现……不过，端口占用的问题我也考虑到了，如果被占用了会自动更换一个别的端口，可能这部分还是有点问题。

**Comment by 1Crazy** [comment]
我的也是404。。。发现端口没有被占用

**Comment by SaekiRaku** [comment]
@1Crazy 您好，请问您打开浏览器后，显示的直接是 `404 Not Found` 还是 `Cannot GET /` ?

**Comment by 1Crazy** [comment]
404,看了下是因为端口7777被另一个程序占用了，这个能自己手动去更换一个他的端口吗

**Comment by SaekiRaku** [comment]
重写了寻找可用端口的模块，发布了一个新版本 1.2.3，应该解决了这个问题了。

**Comment by xuya227939** [comment]
好的，我试试。

佐伯楽 <notifications@github.com> 于2020年6月22日周一 下午9:38写道：
