### ISSUE TITLE
好东西啊 希望多适配一点语音

### ISSUE THREAD

**Issue by 547daxia** [SaekiRaku/vscode-rainbow-fart#39]

**Comment by HanyuWu** [comment]
给你一个目力前辈包　
[smelling-voice.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4807736/smelling-voice.zip)

只要for 就能听到目力前辈的叫声了

**Comment by hebtuerror404** [comment]
喜欢听小哥哥的声音:)
建议适配XD

**Comment by Sirlanri** [comment]
可以加个“自定义语音”，比如把自己女朋友的声音录进去:D

**Comment by SaekiRaku** [comment]
Closed due to no more reply. And, for now, we have got more voice packages, you can find theme at here: https://saekiraku.github.io/vscode-rainbow-fart/#/zh/awesome-rainbow-fart.md
