### ISSUE TITLE
It's niubi... Could you please publish it to vscode store?

### ISSUE THREAD

**Issue by shrinktofit** [SaekiRaku/vscode-rainbow-fart#4]
BTW, this extension may let programmer GIAO'ers（程序员鼓励师） lose their job!

**Comment by SaekiRaku** [comment]
Thanks, the VSCode store is a globally place, some non-chinese user may installed this extension and not able to use. So, I'm considering to add an English version voice package before publish it to VSCode store. It may be done by tomorrow.

**Comment by myst729** [comment]
Might be off-topic, but who's Alice Moon, any information? 😃

**Comment by SaekiRaku** [comment]
@myst729 She is a friend of mine 🌝

**Comment by iamxie1127** [comment]
> Thanks, the VSCode store is a globally place, some non-chinese user may installed this extension and not able to use. So, I'm considering to add an English version voice package before publish it to VSCode store. It may be done by tomorrow.

So, tomorrow has English version ?  Looking forward to your publish it : )

**Comment by CapAllen** [comment]
> 
> 
> BTW, this extension may let programmer GIAO'ers（程序员鼓励师） lose their job!

`programmer GIAO'ers `, LOL

**Comment by XGHeaven** [comment]
@myst729 Alice Moon? What's this?

**Comment by gafish** [comment]
> @myst729 Alice Moon? What's this?

the author of the built-in voice

**Comment by vczh** [comment]
> It may be done by tomorrow.

It has been yesterday!

**Comment by SaekiRaku** [comment]
@vczh 感谢您的关注！现已发布到 VSCode 商店：https://marketplace.visualstudio.com/items?itemName=saekiraku.rainbow-fart
