### ISSUE TITLE
【已出】强烈请求各位路过大佬赶紧出一个钉宫四萌辱骂合集语音包！

### ISSUE THREAD

**Issue by zthxxx** [SaekiRaku/vscode-rainbow-fart#40]
哪个男孩能拒绝一个傲娇萝莉纸片人老婆在一旁鞭写鞭骂呢？

![image](https://user-images.githubusercontent.com/15135943/85229141-beb67780-b41a-11ea-90e8-94aa8013bb50.png)

-------------------------

...

(Update 一天后)

草，生了出来

根据楼下 @moonlitht 提供的切分语音做了一个包出来！

文件放出来了，  https://github.com/zthxxx/kugimiya-rainbow-fart

有需要的钉宫病患者可以直接在 [releases](https://github.com/zthxxx/kugimiya-rainbow-fart/releases) 这里下载感受

![image](https://user-images.githubusercontent.com/15135943/85218690-28109900-b3cf-11ea-8ae9-7819f589a3d6.png)

**Comment by cloverland** [comment]
> 哪个男孩能拒绝一个傲娇萝莉纸片人老婆在一旁鞭写鞭骂呢？

草（赞赏）

**Comment by moonlitht** [comment]
0人血书请愿

**Comment by KirisakiAria** [comment]
草

**Comment by youyiqin** [comment]
...................

**Comment by lieuxs** [comment]
二营长，你TND意大利炮呢

**Comment by huaji0353** [comment]
语言包有，不太好做的

kiss的感觉好吗？.wav
Windows关闭.wav                    Windows发来警告.wav                Windows启动.wav
不可以着急哦.wav                   偶尔也想被叫一回姐姐.wav           前辈！要不要一起回去？.wav
努力！.wav                         叮铃铃.wav                         可爱的草莓怎么样？.wav
呜哇？.wav                         呜～好慢好慢…….wav                 呜～我要哭啦～！.wav
和哥哥两个人哦.wav                 哦呵呵～.wav                       唱机关闭.wav
唱机启动.wav                       啊呼～.wav                         喵喵！这是病毒～！？.wav
好困…….wav                         好好吃吧.wav                       媒体播放器关闭.wav
媒体播放器启动.wav                 建议扫描磁盘.wav                   快起床！.wav
我一直单恋你.wav                   我可以挽哥哥的胳膊吗？.wav         戴上猫耳可爱吗？.wav
扩大.wav                           抱抱.wav                           抱抱好吗？.wav
是！.wav                           是，我会努力的！.wav               最喜欢哥哥了！.wav
最大化.wav                         最小化.wav                         来邮件了.wav
清空回收站.wav                     电话留言.wav                       真是的！只能一下下哦.wav
真是的，不要碰奇怪的地方啦～.wav   砰.wav                             确认.wav
程序出错.wav                       程序运行.wav                       系统出错.wav
给，我把邮件取回来了.wav           缩小.wav                           网络连接断开.wav
老公～！.wav                       能再撒下娇吗？.wav                 要不要吃苹果派？.wav
要对我好点哦.wav                   警告.wav                           请选择菜单.wav
运行.wav                           连接至网络.wav                     选这些就可以了？.wav
釘宮理恵自我介绍.wav               锵～锵～.wav                       骑过牛吗？.wav

**Comment by moonlitht** [comment]
[dinggong.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4808255/dinggong.zip)
自己找了网上一段钉宫合集剪辑出来的语音包，大家可以试试，滑稽

**Comment by moonlitht** [comment]
[dinggong.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4808260/dinggong.zip)
索性自己动手制作的一个语音包，网上找的语音合集剪辑下来的

**Comment by c987617162** [comment]
草

**Comment by zthxxx** [comment]
按 @moonlitht 提供的素材尝试打出了一个包，

https://github.com/zthxxx/kugimiya-rainbow-fart

楼上各位要不要尝一口呐？  @cloverland @KirisakiAria @lieuxs @huaji0353

**Comment by werifu** [comment]
草

**Comment by zombie110year** [comment]
ここの人々は変態ですか？

**Comment by NewBugger** [comment]
ありがとうございました！

**Comment by Alwayslazydog** [comment]
蹲一个

**Comment by fawdlstty** [comment]
readme.md里面维护这么一个语音包列表比较好

**Comment by SaekiRaku** [comment]
@fawdlstty 目前已在文档中维护：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/README.md#更多炫酷彩虹屁

**Comment by zthxxx** [comment]
> readme.md里面维护这么一个语音包列表比较好

虽然不在 README 里面，但在官网页面里有

 https://saekiraku.github.io/vscode-rainbow-fart/#/zh/#%E8%AF%AD%E9%9F%B3%E5%8C%85-2

**Comment by Aufree** [comment]
是否可以考虑直接用这个 GitHub 项目来克隆语音包：

https://github.com/CorentinJ/Real-Time-Voice-Cloning
