### ISSUE TITLE
希望解决每次都需要开启浏览器才能发声的问题

### ISSUE THREAD

**Issue by muyichenfeng** [SaekiRaku/vscode-rainbow-fart#43]
希望解决每次都需要开启浏览器才能发声的问题，并且每次运行都需要打开进行操作过于麻烦，希望改进。谢谢。

**Comment by SaekiRaku** [comment]
感谢反馈，目前正在考虑采用 https://github.com/SaekiRaku/vscode-rainbow-fart/issues/34 这个方案，如果还有其他更好的方案，也欢迎提出一同探讨。

**Comment by yuyuyuyuyu1234** [comment]
钢琴声音也听见了  为啥还是听不见  那个萌妹子的声音，求问
