### ISSUE TITLE
我发现我安装了不会用，，，没有声音，你能帮帮我吗？

### ISSUE THREAD

**Issue by hys666666** [SaekiRaku/vscode-rainbow-fart#5]

**Comment by SaekiRaku** [comment]
是按照文档上的操作步骤操作的吗？现在看到打开的页面了吗？方便截图一下打开的页面和开发者工具控制台吗，看一下有没有控制台报错和网络错误？

**Comment by hys666666** [comment]
![Uploading SharedScreenshot.jpg…]()
就这样

**Comment by hys666666** [comment]
添加了vsix文件后，右下角显示了成功安装，没看到有报错，

**Comment by hys666666** [comment]
> 是按照文档上的操作步骤操作的吗？现在看到打开的页面了吗？方便截图一下打开的页面和开发者工具控制台吗，看一下有没有控制台报错和网络错误？

图片在这：https://s1.ax1x.com/2020/06/18/Ne7upq.jpg

**Comment by SaekiRaku** [comment]
@hys666666 你看一下文档的[运行说明](https://saekiraku.github.io/vscode-rainbow-fart/#/zh/#安装与使用)，因为插件会占用一些资源，所以默认不是自动启动的，需要手动启动一下。并且由于 VSCode 限制，需要借助浏览器播放音频。

![QQ20200618-145012](https://user-images.githubusercontent.com/12109558/84987854-88a39a00-b173-11ea-998b-c603f0834daa.png)

**Comment by hys666666** [comment]
> @hys666666 你看一下文档的[运行说明](https://saekiraku.github.io/vscode-rainbow-fart/#/zh/#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8)，因为插件会占用一些资源，所以默认不是自动启动的，需要手动启动一下（命令面板 -> Enable Rainbow Fart）。并且由于 VSCode 限制，需要借助浏览器播放音频，所以需要点击 Open 打开网页，并点击网页上的授权音频播放的按钮。
> 
> ![QQ20200618-145012](https://user-images.githubusercontent.com/12109558/84987854-88a39a00-b173-11ea-998b-c603f0834daa.png)

http://127.0.0.1:7777/谷歌浏览器和IE浏览器都访问失败

**Comment by SaekiRaku** [comment]
@hys666666 就是，执行完 `> Enable Rainbow Fart` 命令后有看到右下角的弹窗吗？端口实际上是动态获取的，有可能不是 7777 要以本机为准，建议你是直接点击弹出的消息窗口上的 Open 按钮。

<img width="467" alt="QQ20200618-150213@2x" src="https://user-images.githubusercontent.com/12109558/84988543-c5bc5c00-b174-11ea-97aa-4c722d278ad7.png">

**Comment by hys666666** [comment]
嗷！我搞定了，谢谢
