### ISSUE TITLE
英文版的内置语音很棒，希望能继续丰富内容 Built-in English voice is great, pls add more

### ISSUE THREAD

**Issue by RATCH3T7537** [SaekiRaku/vscode-rainbow-fart#50]
如题，其实男声也可以这样。
Actually, you may offer a male version of English voice package in the same way. Good work and keep going!

**Comment by SaekiRaku** [comment]
Thanks，作为内置语音包，目前还是比较期望有机会可以由以英语为母语的开源社区贡献者进行录制，避免一些口音等问题。目前的语音合成只是临时策略。
