### ISSUE TITLE
How can I support a anchor language?

### ISSUE THREAD

**Issue by zbwxtex** [SaekiRaku/vscode-rainbow-fart#51]
我该如何制作一个(附属插件?)对其他语言进行支持, 如Java和ASM

**Comment by SaekiRaku** [comment]
@zbwxtex 请参阅《定制语音包》：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md ，定制完成的语音包，通过 WEB 界面直接导入即可。如果您的语音包打算公开给社区，可以新建一个仓库存储，并增加 `rainbow-fart` 话题（topic）以方便其他用户检索。

**Comment by SaekiRaku** [comment]
Closed due to no more response, feel free to reopen.
