### ISSUE TITLE
什么时候可以对其他语言的支持

### ISSUE THREAD

**Issue by zhujingzhi** [SaekiRaku/vscode-rainbow-fart#54]
作者大佬 什么时候可以加一下对 Python 和 Go 语言的支持  😁

**Comment by SaekiRaku** [comment]
我更新了一个 1.2.2 版本，扩充了内置语音包的关键字，适配了一些其他语言。但是语音内容的增加，期望于社区的贡献。另附: https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2
