### ISSUE TITLE
按照步骤成功后，编码关键字，但是报了图片这个错误

### ISSUE THREAD

**Issue by huahuazfh** [SaekiRaku/vscode-rainbow-fart#56]
![image](https://user-images.githubusercontent.com/37288392/85240382-90f91f00-b46a-11ea-88c3-a66f9556596e.png)

**Comment by SaekiRaku** [comment]
Hi, 这个错误应该是正常的，Web 上的语音播放依赖于和 VSCode 扩展的交互。我这里是通过 HTTP 长轮询实现的，因此如果 VSCode 长时间没有输入，扩展就不会对播放请求进行响应，此时若请求超时Web控制台会出现此错误。

如果您在修改关键字后没有生效，只需要点击页面上的 `刷新` 即可。

**Comment by huahuazfh** [comment]
你好 我刷新了页面点击了授权听到了钢琴声 输入一些关键字也是没有声音




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"佐伯楽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 上午10:42
收件人:&nbsp;"SaekiRaku/vscode-rainbow-fart"<vscode-rainbow-fart@noreply.github.com&gt;;
抄送:&nbsp;"叶落枫飘"<961409742@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [SaekiRaku/vscode-rainbow-fart] 按照步骤成功后，编码关键字，但是报了图片这个错误 (#56)





 
Hi, 这个错误应该是正常的，Web 上的语音播放依赖于和 VSCode 扩展的交互。我这里是通过 HTTP 长轮询实现的，因此如果 VSCode 长时间没有输入，扩展就不会对播放请求进行响应，此时若请求超时Web控制台会出现此错误。
 
如果您在修改关键字后没有生效，只需要点击页面上的 刷新 即可。

**Comment by SaekiRaku** [comment]
@huahuazfh 您好，可以在 VSCode 的命令版里执行 `> Help: About` 这个命令，提供一下系统信息吗？我看看我这边能否复现这个问题。

**Comment by huahuazfh** [comment]
版本: 1.35.1
提交: c7d83e57cd18f18026a8162d042843bda1bcf21f
日期: 2019-06-12T14:29:22.216Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.6.0





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"佐伯楽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 中午11:01
收件人:&nbsp;"SaekiRaku/vscode-rainbow-fart"<vscode-rainbow-fart@noreply.github.com&gt;;
抄送:&nbsp;"叶落枫飘"<961409742@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SaekiRaku/vscode-rainbow-fart] 按照步骤成功后，编码关键字，但是报了图片这个错误 (#56)





 
@huahuazfh 您好，可以在 VSCode 的命令版里执行 &gt; Help: About 这个命令，提供一下系统信息吗？我看看我这边能否复现这个问题。

**Comment by SaekiRaku** [comment]
Hi，感谢反馈。我现在大致定位到问题了（旧版本的 VSCode 未提供 vscode.workspace.fs 对象），但是目前我建议你直接升级 VSCode 版本（我使用的是 1.46.1），这是修复启动问题最快的方法。

因为所有低于 1.40 的 VSCode 版本，均发布于 1 年前。这个时间跨度有点大，很多 VSCode API 都改变了。当调用旧版本不存在的 API 时，流程就卡住了。我可以修复这个问题，但是需要一些时间来定位所有变更过的 API，并写出兼容代码。

**Comment by huahuazfh** [comment]
好的，谢谢，我升级最新版的vscode，已经可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"佐伯楽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 中午1:43
收件人:&nbsp;"SaekiRaku/vscode-rainbow-fart"<vscode-rainbow-fart@noreply.github.com&gt;;
抄送:&nbsp;"张枫鸿"<961409742@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SaekiRaku/vscode-rainbow-fart] 按照步骤成功后，编码关键字，但是报了图片这个错误 (#56)





 
Hi，感谢反馈。我现在大致定位到问题了（旧版本的 VSCode 未提供 vscode.workspace.fs 对象），但是目前我建议你直接升级 VSCode 版本（我使用的是 1.46.1），这是修复启动问题最快的方法。
 
因为所有低于 1.40 的 VSCode 版本，均发布于 1 年前。这个时间跨度有点大，很多 VSCode API 都改变了。当调用旧版本不存在的 API 时，流程就卡住了。我可以修复这个问题，但是需要一些时间来定位所有变更过的 API，并写出兼容代码。
