### ISSUE TITLE
非JS支持?

### ISSUE THREAD

**Issue by sahuang** [SaekiRaku/vscode-rainbow-fart#58]
如题,使用VSCode开发C++,但是自己制作语音包的时候仅有if for等少量关键词能触发语音机制.

想问下之后是否计划多加些关键词,比如vector include namespace struct ::等..

**Comment by sahuang** [comment]
好像有定制语音包,那没事了.

**Comment by SaekiRaku** [comment]
Hi, 感谢您的反馈。目前语音包支持一些简单定制，扩展关键字其实是比较容易的，比较困难的是录制更多贴合代码的语音资源，这需要很多时间和精力。如果您觉得目前内置的语音包的语音资源与您所使用的语言的某些关键字比较贴切，但是却没有触发。您也可以自行修改内置语音包，方法如下：

1. 点击 Web 界面上的 `打开语音包目录` 按钮。
2. 在打开的目录中复制 `built-in-voice-chinese` 并更改一个其他名字，例如 `customize-01`
3. 修改 `customize-01` 目录中 `manifest.json` 的 name 字段，确保其与其他语音包的 name 没有重名。
4. 修改 `customize-01` 目录中 `contributes.json` 的相关 keywords 字段来增加关键词。
5. 修改完成后点击 Web 界面上的刷新按钮。

**Comment by sahuang** [comment]
恩,我看到了,谢谢!
