### ISSUE TITLE
vscode没有声音

### ISSUE THREAD

**Issue by snoopy1412** [SaekiRaku/vscode-rainbow-fart#59]
环境：osx系统
vscode版本：1.33.1
按照步骤操作没有声音，很是难受

**Comment by SaekiRaku** [comment]
Hi，感谢反馈。我现在大致定位到问题了（旧版本的 VSCode 未提供 vscode.workspace.fs 对象），但是目前我建议你直接升级 VSCode 版本（我使用的是 1.46.1），这是修复启动问题最快的方法。

因为所有低于 1.40 的 VSCode 版本，均发布于 1 年前。这个时间跨度有点大，很多 VSCode API 都改变了。当调用旧版本不存在的 API 时，流程就卡住了。我可以修复这个问题，但是需要一些时间来定位所有变更过的 API，并写出兼容代码。

**Comment by wxwmaple** [comment]
> 
> 
> Hi，感谢反馈。我现在大致定位到问题了（旧版本的 VSCode 未提供 vscode.workspace.fs 对象），但是目前我建议你直接升级 VSCode 版本（我使用的是 1.46.1），这是修复启动问题最快的方法。
> 
> 因为所有低于 1.40 的 VSCode 版本，均发布于 1 年前。这个时间跨度有点大，很多 VSCode API 都改变了。当调用旧版本不存在的 API 时，流程就卡住了。我可以修复这个问题，但是需要一些时间来定位所有变更过的 API，并写出兼容代码。

v1.46版本同没有声音，只有整点报时，但无法检测vscode代码里的关键词

**Comment by SaekiRaku** [comment]
@wxwmaple 感谢反馈！可以麻烦提供一下详细信息吗？

1. 执行 VSCode 命令 `> Help: About` 后得到的内容
2. 您测试时输入过的关键词
3. 界面中右侧下方是否可见语音包列表

**Comment by wxwmaple** [comment]
> 
> 
> @wxwmaple 感谢反馈！可以麻烦提供一下详细信息吗？
> 
>     1. 执行 VSCode 命令 `> Help: About` 后得到的内容
> 
>     2. 您测试时输入过的关键词
> 
>     3. 界面中右侧下方是否可见语音包列表

辛苦答主了，我发现授权成功后还要点击相应的语音包开关就能工作

**Comment by SaekiRaku** [comment]
@wxwmaple 嗯嗯，初始启动的时候，其实会判断当前的 VSCode 所使用的语言环境来默认激活英语或汉语的内置语音包。可能是您 VSCode 当前的语言设置，导致没有默认激活中文语音包。

**Comment by XingXiaoWu** [comment]
> > @wxwmaple 感谢反馈！可以麻烦提供一下详细信息吗？
> > ```
> > 1. 执行 VSCode 命令 `> Help: About` 后得到的内容
> > 
> > 2. 您测试时输入过的关键词
> > 
> > 3. 界面中右侧下方是否可见语音包列表
> > ```
> 
> 辛苦答主了，我发现授权成功后还要点击相应的语音包开关就能工作

在哪授权开关呢

**Comment by XingXiaoWu** [comment]
找到了，是在授权的时候，把下面的语音包的开关，开关一下

**Comment by snoopy1412** [comment]
> Hi，感谢反馈。我现在大致定位到问题了（旧版本的 VSCode 未提供 vscode.workspace.fs 对象），但是目前我建议你直接升级 VSCode 版本（我使用的是 1.46.1），这是修复启动问题最快的方法。
> 
> 因为所有低于 1.40 的 VSCode 版本，均发布于 1 年前。这个时间跨度有点大，很多 VSCode API 都改变了。当调用旧版本不存在的 API 时，流程就卡住了。我可以修复这个问题，但是需要一些时间来定位所有变更过的 API，并写出兼容代码。

感谢，成功连接上萌妹子，希望以后开发更多功能哈
