### ISSUE TITLE
AndroidStudio need this,plz!!!!!!!

### ISSUE THREAD

**Issue by Mystery007** [SaekiRaku/vscode-rainbow-fart#6]

**Comment by SaekiRaku** [comment]
I basically only use VSCode at work, so I'm not familiar with the API of other editor or IDE. It will take more time to transplant this extension. But still, it's on the plan and if anyone familiar with others API, welcome to push PR.

(Mark for myself: Similar with https://github.com/SaekiRaku/vscode-rainbow-fart/issues/3#issuecomment-645786218)

**Comment by IAmWilling** [comment]
考虑出一个AndroidStudio的呗

**Comment by izhangzhihao** [comment]
Here you are: https://github.com/izhangzhihao/intellij-rainbow-fart

**Comment by SaekiRaku** [comment]
Closed, please refer to https://github.com/izhangzhihao/intellij-rainbow-fart
