### ISSUE TITLE
function.mp3 在 2 秒的時候出現噴麥聲

### ISSUE THREAD

**Issue by livekn** [SaekiRaku/vscode-rainbow-fart#62]
function.mp3 在 2 秒的時候會出現噴麥聲，希望可以提高錄音品質

**Comment by SaekiRaku** [comment]
😁感谢反馈，项目纯兴趣及娱乐性质，没有设置太专业的设备。尽管现有语音包已通过 Audio 尽可能的抑制喷麦音了，不过仍有部分不太好剔除。后期抽空重录部分资源。
