### ISSUE TITLE
an error with refresh browser not vaild

### ISSUE THREAD

**Issue by ajinwu** [SaekiRaku/vscode-rainbow-fart#75]
platform: windows10
browser: chrome

when i use it, i click that Permission button, I can listen piano sound, but I go to vscode, that is not run, I need refresh page and retry to click, and not to use it

**Comment by SaekiRaku** [comment]
Cloud you please provide more detailed information? Please run VSCode command: `> Help: About` and copy & paste the output to here.

**Comment by SaekiRaku** [comment]
Close due to no more respond, feel free to reopen this issue.
