### ISSUE TITLE
自定义关键字能不能直接修改manifest.json

### ISSUE THREAD

**Issue by xiangyaogezhongerdemingzi** [SaekiRaku/vscode-rainbow-fart#76]
如题，但是我修改后声音全没有了

**Comment by SaekiRaku** [comment]
您可以贴一下具体修改了哪些内容，我好确定具体问题。另外，如果是内置语音包，则关键字是在 `contributes.json` 里。

相关文档：
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#如何修改内置语音包（增加修改关键字等）
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md

**Comment by SaekiRaku** [comment]
Close due to no more respond, feel free to reopen this issue.
