### ISSUE TITLE
http://127.0.0.1:7777/无法打开

### ISSUE THREAD

**Issue by linguo2625469** [SaekiRaku/vscode-rainbow-fart#8]
无法访问此网站

**Comment by SaekiRaku** [comment]
请对照文档的步骤启动。安装完后，还需要在命令面板执行 `> Enable Rainbow Fart` 才能启动扩展，端口是动态获取的，有可能不是 `7777`，要以启动后右下角的消息弹窗的地址为准，建议你直接点击消息弹窗上的 Open 按钮打开。

SImilar with: https://github.com/SaekiRaku/vscode-rainbow-fart/issues/5#issuecomment-645822688

**Comment by linguo2625469** [comment]
> 请对照文档的步骤启动。安装完后，还需要在命令面板执行 `> Enable Rainbow Fart` 才能启动扩展，端口是动态获取的，有可能不是 `7777`，要以启动后右下角的消息弹窗的地址为准，建议你直接点击消息弹窗上的 Open 按钮打开。
> 
> SImilar with: [#5 (comment)](https://github.com/SaekiRaku/vscode-rainbow-fart/issues/5#issuecomment-645822688)

我是输入> Enable Rainbow Fart后点击右下角open打开的 还是不行。。不知道为什么

**Comment by SaekiRaku** [comment]
@linguo2625469 方便提供一下系统版本和 VSCode 版本吗？我看看我这里能不能复现这个问题。

**Comment by linguo2625469** [comment]
@SaekiRaku Windows 10 专业版 2004
vscode 1.46.1

**Comment by SaekiRaku** [comment]
@linguo2625469 这个 Windows 版本是 Insider 的吗？我的虚拟机目前不支持升级到这个系统版本。我使用 1.46.1 的 VSCode 测试了一下无法复现这个问题。您方便克隆一下本项目在本地调试一下并贴出报错吗？

步骤：
1. 卸载插件。
2. 克隆项目，然后执行 `npm install` 安装依赖。
3. 在 VSCode 的调试面板运行 `Run Extension`。
<img width="353" alt="QQ20200619-111541@2x" src="https://user-images.githubusercontent.com/12109558/85093323-864a4a00-b21e-11ea-9562-eb3de6b2d531.png">
4. 检查调试控制台面板的输出。
<img width="1145" alt="QQ20200619-111608@2x" src="https://user-images.githubusercontent.com/12109558/85093307-7cc0e200-b21e-11ea-86f1-dca6b0145630.png">

**Comment by linguo2625469** [comment]
按照步骤运行后 调试控制台打印如下  @SaekiRaku 
`Git installation not found.
main.js:1
c:\Users\rj\AppData\Roaming\Code\User\globalStorage\saekiraku.rainbow-fart
assets.js:14
Playing voice - undefined
share.js:9
EntryNotFound (FileSystemError): 无法读取文件'c:\Users\rj\AppData\Roaming\Code\User\globalStorage\saekiraku.rainbow-fart\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\rj\AppData\Roaming\Code\User\globalStorage\saekiraku.rainbow-fart\settings.json')
	at _handleError (c:\Users\rj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:666:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.load (c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\settings.js:37:32)
settings.js:39
rejected promise not handled within 1 second: TypeError: Cannot read property 'version' of undefined
extensionHostProcess.js:976
stack trace: TypeError: Cannot read property 'version' of undefined
	at Object.init (c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\assets.js:43:32)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)`

**Comment by SaekiRaku** [comment]
@linguo2625469 我推送了一份新代码，麻烦你下拉一下然后再运行以下，看看调试控制台的报错。

**Comment by linguo2625469** [comment]
c:\Users\rj\AppData\Roaming\Code\User\globalStorage\saekiraku.rainbow-fart
assets.js:14
EntryNotFound (FileSystemError): 无法读取文件'c:\c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\built-in-voice-packages\built-in-voice-chinese\manifest.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\built-in-voice-packages\built-in-voice-chinese\manifest.json')
	at _handleError (c:\Users\rj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:666:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.init (c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\assets.js:40:46)
assets.js:43
rejected promise not handled within 1 second: TypeError: Cannot read property 'version' of undefined
extensionHostProcess.js:976
stack trace: TypeError: Cannot read property 'version' of undefined
	at Object.init (c:\Users\rj\Desktop\vscode-rainbow-fart-master\src\assets.js:45:32)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by SaekiRaku** [comment]
@linguo2625469 抱歉让你久等了，我想办法在虚拟机里安装上 Windows 2004 了，问题成功复现。麻烦你再次下拉代码，然后执行 `npm run build` ，然后安装项目目录下生成的 VSIX 即可，应该可以正常使用了。

**Comment by linguo2625469** [comment]
npm run build

> rainbow-fart@1.1.0 build C:\Users\rj\Desktop\vscode-rainbow-fart-master
> rm -rf src/page/dist && node -r esm scripts/before-build.js && npm run build:page && vsce package && node -r esm scripts/after-build.js

'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rainbow-fart@1.1.0 build: `rm -rf src/page/dist && node -r esm scripts/before-build.js && npm run build:page && vsce package && node -r esm scripts/after-build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rainbow-fart@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rj\AppData\Roaming\npm-cache\_logs\2020-06-19T05_53_28_628Z-debug.log


是windows不支持这个命令吗？报错如上 @SaekiRaku

**Comment by SaekiRaku** [comment]
@linguo2625469 没有 rm 命令，手动删除一下 `src/page/dist`（如果有），然后手动执行下 `node -r esm scripts/before-build.js && npm run build:page && vsce package && node -r esm scripts/after-build.js` 这个命令就行了（在 package.json 所在目录下）

**Comment by linguo2625469** [comment]
@SaekiRaku 编译后导入成功 开启会报错 不知道哪一步出问题了  大佬有空更新一下版本吧哈哈
命令"🌈 Enable Rainbow Fart"导致错误 (command 'rainbow-fart.enable' not found)

**Comment by SaekiRaku** [comment]
[rainbow-fart-1.1.1.vsix.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4807305/rainbow-fart-1.1.1.vsix.zip)

试试看这个

**Comment by linguo2625469** [comment]
@SaekiRaku 你好 安装了最新版 进入http://127.0.0.1:7777/还是无法访问 但是http://localhost:7777/可以正常访问
