### ISSUE TITLE
东北妹子听不下去，能不能让我贡献下东北话版本的？

### ISSUE THREAD

**Issue by lhli3** [SaekiRaku/vscode-rainbow-fart#81]
同事表示很期待我的东北话版本，就怕上班跟编译器干起来，哈哈哈哈哈哈，画面太美

**Comment by SaekiRaku** [comment]
感谢关注，欢迎贡献！语音包定制文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md

**Comment by ycp424c** [comment]
期待东北话版本+1

**Comment by wangwu1** [comment]
期待+1

**Comment by lhli3** [comment]
这个端午假期整一波

**Comment by lhli3** [comment]
有没有别人写好的配置，有一些关键字可能我的不够全，

> 感谢关注，欢迎贡献！语音包定制文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/voice-packages.md

**Comment by SaekiRaku** [comment]
@lhli3 这个是内置中文语音包的配置，可以参考一下。[built-in-voice-chinese.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4823044/built-in-voice-chinese.zip)

**Comment by lhli3** [comment]
> @lhli3 这个是内置中文语音包的配置，可以参考一下。[built-in-voice-chinese.zip](https://github.com/SaekiRaku/vscode-rainbow-fart/files/4823044/built-in-voice-chinese.zip)

谢谢啦，请问这个除了js还支持其他语言吗比如go?

**Comment by SaekiRaku** [comment]
@lhli3 可以，插件本身没有对文件类型和语言标识符做检测，只需要在 contributes.json 文件中的 keywords 字段里设置关键字就行了，比如需要响应 `func`，就直接：

```
{
    "keywords": [ "func" ],
    "voices": [ "语音文件名.mp3" ]
}
```
