### ISSUE TITLE
[Feature] 能否增加对其他语言的支持？

### ISSUE THREAD

**Issue by forMwish** [SaekiRaku/vscode-rainbow-fart#82]
**Describe your request**
感觉挺有意思的，能否增加对 python、C 的支持？

**Comment by SaekiRaku** [comment]
单纯的增加语言关键字并不困难，比较麻烦的是增加与关键字相关的配音，这一点我比较期望由社区贡献更多的语音（请参阅：https://github.com/SaekiRaku/vscode-rainbow-fart/issues/2 ）。如果您当前觉得某些语言的关键字没有得到适配，可以先临时的自行修改（请参阅：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#如何修改内置语音包（增加修改关键字等） ）
