### ISSUE TITLE
[语音包] 我的青春恋爱物语果然有问题 - 团子语音包

### ISSUE THREAD

**Issue by syang-ng** [SaekiRaku/vscode-rainbow-fart#85]
春物里团子的语音包，团子厨们可以装一个玩玩
东山大法好！
https://github.com/syang-ng/Yuigahama-Yui-rainbow-fart
最后感谢作者提供的插件！

**Comment by SaekiRaku** [comment]
感谢贡献！仓库链接现已加入到文档。
