### ISSUE TITLE
求个java版本的语言包

### ISSUE THREAD

**Issue by Un-KnownCode** [SaekiRaku/vscode-rainbow-fart#86]
编写java的时候输入一个判断=>就给出函数箭头的语音，而且很多关键字是java不用的，若是有适合java的语音包就好了

**Comment by SaekiRaku** [comment]
抱歉，回复的有些晚了。目前关于特定语言的判断的实现还没有决定，当前可行的方法是自行修改语音包配置文件，详见文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E5%86%85%E7%BD%AE%E8%AF%AD%E9%9F%B3%E5%8C%85%EF%BC%88%E5%A2%9E%E5%8A%A0%E4%BF%AE%E6%94%B9%E5%85%B3%E9%94%AE%E5%AD%97%E7%AD%89%EF%BC%89
