### ISSUE TITLE
会出idea的嘛

### ISSUE THREAD

**Issue by 1952998569** [SaekiRaku/vscode-rainbow-fart#87]

**Comment by SaekiRaku** [comment]
Please refer to:
- https://github.com/izhangzhihao/intellij-rainbow-fart
- https://saekiraku.github.io/vscode-rainbow-fart/#/zh/awesome-rainbow-fart.md#其他客户端

**Comment by jadepeng** [comment]
https://github.com/jadepeng/idea-rainbow-fart
