### ISSUE TITLE
能支持Android Studio么？膜拜大佬了🤣

### ISSUE THREAD

**Issue by kaina404** [SaekiRaku/vscode-rainbow-fart#9]

**Comment by SaekiRaku** [comment]
抱歉，平时工作中主要使用 VSCode，对其他 编辑器/IDE 的开放 API 不太熟悉。插件移植是在计划中的，但是可能会需要较长的时间。如果有熟悉其他任意编辑器或IDE的开放API的开发者，欢迎提交PR。

Similar with:
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/6
- https://github.com/SaekiRaku/vscode-rainbow-fart/issues/3#issuecomment-645786218

**Comment by SaekiRaku** [comment]
Closed, please refer to https://github.com/izhangzhihao/intellij-rainbow-fart

**Comment by kaina404** [comment]
Android Studio版本的我昨天写好了
