### ISSUE TITLE
[Question] If you have enough time,Can you support the plug-in of idea? 恳求出IDEA的插件

### ISSUE THREAD

**Issue by hyjsnbb** [SaekiRaku/vscode-rainbow-fart#90]
救救Java空巢老人!
Please help the empty nest old man of Java!

**Comment by SaekiRaku** [comment]
IDEA 插件已有社区贡献，其他编辑器/IDE的客户端，请参见文档：https://saekiraku.github.io/vscode-rainbow-fart/#/zh/awesome-rainbow-fart.md#%E5%85%B6%E4%BB%96%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by hyjsnbb** [comment]
thanks
