### ISSUE TITLE
你们是真的无聊

### ISSUE THREAD

**Issue by petsgre** [SaekiRaku/vscode-rainbow-fart#91]
。。。

**Comment by SaekiRaku** [comment]
Please refer to https://saekiraku.github.io/vscode-rainbow-fart/#/zh/qa.md#%E6%8F%92%E4%BB%B6%E7%9A%84%E6%84%8F%E4%B9%89%EF%BC%9F%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BC%80%E5%8F%91%E8%BF%99%E4%B8%AA%E6%8F%92%E4%BB%B6%EF%BC%9F
