### ISSUE TITLE
[Question]  关于插件判断触发语音的逻辑是什么样的

### ISSUE THREAD

**Issue by Haven09** [SaekiRaku/vscode-rainbow-fart#92]
**Describe your question**

**What did you do before you hit this problem**

**Information**

不知道插件判断的原理是什么，不过好像如果使用ide的联想输入关键字，貌似是触发不了语音
**Additional Context**

**Comment by SaekiRaku** [comment]
插件是通过 `vscode.workspace.onDidChangeTextDocument` 事件捕获输入内容的，正常情况下输入、联想、格式化均会触发此事件。但是，插件判断了如果一次性输入的字符数超过30则不会触发语音。比如格式化操作会将整个文件的内容传入事件，这样就无法判断用户刚刚输入的内容了，所以这里判断字符数大致超过30个就不属于关键字了。因此，如果你的 `Code Snippets` 配置联想到了超过 30 字符的代码提示，则不会触发语音。

**Comment by Haven09** [comment]
好的
