### ISSUE TITLE
[语音包]恋与制作人凌肖语音包

### ISSUE THREAD

**Issue by racherisgenius** [SaekiRaku/vscode-rainbow-fart#96]
难道程序媛不配拥有野男人自身边？（还是说就我一个会用…）
抽了点时间做了个凌肖的语音包，第一次学会在github上面上传文件和写readme，非常有意思！
非常感谢作者的插件！给了我男人也给了我快乐！深夜写码的我再也不寂寞了！
https://github.com/racherisgenius/Choudidi-rainbow-fart

**Comment by SaekiRaku** [comment]
感谢贡献，仓库链接已加入到文档。
